# Generated by Django 5.1.4 on 2025-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_data',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='r_data',
            name='Contact',
            field=models.IntegerField(),
        ),
    ]
